### ISSUE TITLE
Druid of the Wastes hybrid variant is missing

### ISSUE THREAD

**Issue by silasary** [CBLoader/CBParts#1]

**Comment by thoth-process** [comment]
All three sentinel hybrid season choice options have errors:
* Wastes: is not present despite being allowed by Dragon 400 and HotEC; the Hybrid Talent options are already present except for Animal Companion Power.
* Summer: Hybrid Talent - Animal Companion Power, Summer hybrid sentinels do not receive the Bear power
* Spring: Hybrid Talent - Animal Companion Power, Spring hybrid sentinels receive both the Wolf and Bear powers.
