### ISSUE TITLE
School of Magic feats - wrong prereq, feature select is messy

### ISSUE THREAD

**Issue by thoth-process** [CBLoader/CBParts#136]
School of Magic Apprentice allows selection as a Witch, Sha'ir, Bladesinger, or Hybrid Wizard without Arcane Implement Mastery.

School of Magic Expert lists its prerequisite as 10th level incorrectly.

All three, in the select, have themselves listed as an option. They should just grant the features rather than having a select identical to the feature category.

**Comment by silasary** [comment]
From memory, the Select thing was there for a reason.  But the Google Wave discussions as to why it was correct are long gone.
