### ISSUE TITLE
Orium Implement is "Other"

### ISSUE THREAD

**Issue by silasary** [CBLoader/CBParts#2]
> ooo, if we're talking about fixes in the CB, the Orium Implement doesn't work right.  It's in the 'other' category instead of with individual implements and it can't be equipped properly

**Comment by thoth-process** [comment]
Any fix to Orium Implement can also be applied to Chaos Shard Implement, which is in the same state.

**Comment by thoth-process** [comment]
Based off how the Controller's Implement (from Revenge of the Giants) was implemented, the fix is likely to be to create separate implement entries for:
* Orium Rod
* Orium Staff
* Orium Rod
* Orium Wand
* Chaos Shard Rod
* Chaos Shard Staff
* Chaos Shard Wand

And then ignore the entries in Other.
