### ISSUE TITLE
cavalier/blackguard/sentinel should be able to pick powers from their parent classes

### ISSUE THREAD

**Issue by silasary** [CBLoader/CBParts#42]

**Comment by thoth-process** [comment]
Research:
Single-classed Cavalier can pick Paladin powers.
Single-classed Blackguard can pick Paladin powers.
Single-classed Sentinel can pick Druid powers.
Hybrid Sentinel can pick Druid encounter powers.
Hybrid Blackguard canNOT pick Paladin encounter powers other than Disheartening Challenge and Weakening Challenge (or Dread Smite)
Hybrid Cavalier canNOT pick Paladin encounter powers other than Disheartening Challenge and Weakening Challenge (or Holy Smite)

This should probably be renamed "Hybrid cavalier/blackguard cannot pick paladin encounter powers"
